### ISSUE TITLE
(SOLVED) Unable to find 'RunHSLExecutor.dll' assembly

### ISSUE THREAD

**Issue by SandorAlbert** [dgretton/pyhamilton#10]
For some reason the 'RunHSLExecutor.dll' assembly is not found.
https://github.com/dgretton/pyhamilton/blob/1a727185a8fa6c665a3b9dbaf4c6360cbf1933e4/pyhamilton/interface.py#L199

```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Vantage\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\Users\Vantage\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Vantage\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhamilton\interface.py", line 137, in run_hamilton_process
    clr.AddReference(os.path.join(OEM_STAR_PATH, 'RunHSLExecutor'))
System.IO.FileNotFoundException: Unable to find assembly 'C:\Users\Vantage\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyhamilton\STAR-OEM\RunHSLExecutor'.
   bei Python.Runtime.CLRModule.AddReference(String name)
```
What I tried:
- Check if the file is present/the directory is correct. It is.
- Check the 'RunHSLExecutor.dll' 'read-only' property (file -> right click -> properties). Was already disabled.
- Check for the correct Python version. I have Python 3.6.3 32 bit as required.
- Check for the correct .Net version. I have >= 4.0.
- Add ".dll" to the directory string, didn't work.

What I noticed:
- If I open 'RunHSLExecutor.dll' using the 'Win 10 Editor' text editor I don't see anything, it's blank. But the file has a size of 16 kb. E.g. in case of 'HSLHttp.dll' I get cryptic symbols. Maybe the file is corrupt?

**SOLUTION:
The file was indeed corrupt. That's weird. I replaced the file with a freshly copied one from this repo and suddenly it worked.**

**Comment by stefangolas** [comment]
Glad to hear you fixed it and thanks for posting your solution
