### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by pickledherring** [dgretton/pyhamilton#13]
I have tried installing via pip and ssh, both have issues either with pythonnet or with HSLJson
![Capture](https://user-images.githubusercontent.com/50645976/190920016-4ddf3a47-1cbf-465f-8dfd-495743949b1a.PNG)
![Capture2](https://user-images.githubusercontent.com/50645976/190920518-0a75d242-2eca-4d7d-847c-96aa1ae5503a.PNG)
This is on a work machine, so it is possible something is being blocked by IT.

**Comment by jrast** [comment]
The error you get in the first screenshot is because the [pythonnet](https://pypi.org/project/pythonnet/) package is not yet released as wheel package for python 3.9. If you can, use python 3.8 which should work.

**Comment by pickledherring** [comment]
excellent, thank you, it worked.
![Capture3](https://user-images.githubusercontent.com/50645976/190929757-882b2036-0f1d-49be-9575-6119ed39e18c.PNG)
