### ISSUE TITLE
[Load New Desk Layout]

### ISSUE THREAD

**Issue by dinhsang1999** [dgretton/pyhamilton#22]
Dear team,
I'm trying to get my app to load and run new .lay and .hsl file, but I'm having an issue with loading a new desk layout. Can you help me troubleshoot the error?
![image](https://user-images.githubusercontent.com/99375579/210930348-17583f44-cd25-495c-aec8-9c99a8f634a2.png)
![image](https://user-images.githubusercontent.com/99375579/210930331-195d410b-3eda-4b15-9ef9-bfddd420b071.png)

**Comment by stefangolas** [comment]
Hi,

What context are you calling the script in? Ie, what terminal application and what command are you using? I've never seen anything that looks like this before.

**Comment by dinhsang1999** [comment]
> Hi,
> 
> What context are you calling the script in? Ie, what terminal application and what command are you using? I've never seen anything that looks like this before.

Hi stengolas,

I will detail all information that you need.

Actually, I established Hamilton Venus and design a custom .med, .hsl, .lay. I want to create a GUI by python to run this and show some information on the GUI from the way that pyhamilton's interfering.

I used Miniconda3 to create ENV following your guides. After that, I loaded the customs files from your libraries but not work.

Window 10 Home
IDE: Visual Studio Code
Terminal application: Window Powershell

**Comment by stefangolas** [comment]
Make sure when you create the virtual environment in Conda you are using Python 3.9 or less. Also, you might have to manually run pip install pywin32==300. It won't work without pywin32==300.

> Actually, I established Hamilton Venus and design a custom .med, .hsl, .lay. I want to create a GUI by python to run this and show some information on the GUI from the way that pyhamilton's interfering.

PyHamilton doesn't work with custom .med files, because it replaces the entire scripting interface of Venus.

**Comment by dinhsang1999** [comment]
Seem to pipywin32==300 is not available now.
![image](https://user-images.githubusercontent.com/99375579/211445801-ad19f3cb-c6e6-4fa3-9101-34d7f7785cc0.png)
About ENV:
![image](https://user-images.githubusercontent.com/99375579/211446231-bdbff045-af56-412d-9374-c124c094a12f.png)

**Comment by stefangolas** [comment]
Ahh, wow! Try installing pywin32 from the installer shown here: https://github.com/mhammond/pywin32/releases/tag/b300

**Comment by stefangolas** [comment]
@dinhsang1999 I actually removed all Win32-dependent code from the repo. It performed a very small and non-essential task, so it was better to remove it since that was a very problematic dependency.
