### ISSUE TITLE
PyHamilton interprets successful Hamilton Heater-Shaker (HHS) operations as failures.

### ISSUE THREAD

**Issue by melkonyan** [dgretton/pyhamilton#25]
PyHamilton server returns status of each operation, whereby `1` is interpreted as 'operation successful' and `0` means a failure.  [source](https://github.com/dgretton/pyhamilton/blob/master/pyhamilton/interface.py#L316)

In the `STAR_OEM_noFan` Venus method, for some HHS operations, operation status is set to the status of the HSLHamHeaterShaker sub-methods, e.g. for commands like `StartShaker`, `StartTempCtl` and some more: 

![image](https://user-images.githubusercontent.com/2010842/232796589-e073cace-2f32-4ea4-8f2b-2113a7ffca0b.png)

Now, the problem is that HSLHamHeaterShaker has different codes, namely `0` means 'operation successful'. As a result, pyhamilton interprets all successful HHS operations as failures. 

![image](https://user-images.githubusercontent.com/2010842/232797217-59204c9b-a008-4500-b6b3-767e63b29f9d.png)

What's the best way to reconcile the status codes? My idea was to just compute pyhamilton status code as `o_stepReturn = hhs_code == 0`.  And then copy the original HHS code to `o_stepReturn2`. Maybe there're better ideas though. 

Let me know, I'm happy to create a pull request with a fix.

**Comment by stefangolas** [comment]
Hi! I thought I had fixed all of these but I guess not. We manually override the conflicting response codes to match the standard format. There should be some examples for other equipment like the tilt module of how this is done, if you want to make a PR.

Thank you!

**Comment by melkonyan** [comment]
Hi Stefan, thanks for the reply! 

Do you do this override in the Venus method or on the python side? I don't see anything like that in the Venus STAR_OEM_noFan method. Where should I look? 

![image](https://user-images.githubusercontent.com/2010842/232804988-715555ad-8aa2-46be-a5c0-16a1b90a6507.png)

**Comment by stefangolas** [comment]
It's handled at the STAR_OEM_Toolkit level, which is an imported submodule library that handles the actual implementation of commands and wraps them with error handling.
![toolkit](https://user-images.githubusercontent.com/32437678/232872475-918681a3-3028-4963-a32c-1224da16ba6c.png)

**Comment by melkonyan** [comment]
aha, I see. You'll have to help me a bit, I'm new to Venus programming. From the documentation of `HSLDaisyChainedTiltModule::MoveToPosition` it looks like it *returns* an error code, and doesn't raise an error via `HSLErrLib::ErrRaise`. In the HSL source code `HSLDaisyChainedTiltModule` I also don't see any error being raised. 

Am I missing something? When writing your code, how did you know that the error is raised and that you have to access `HSLErrLib::ErrGetDataAt(3)`?

**Comment by stefangolas** [comment]
@melkonyan Yes that is exactly right, we try not to raise errors in Venus. Instead, we pass the errors back up to Python via the response string. That way we can have case-by-case error handling implemented at the Python level. The 1s and 0s you are looking at are all about setting values in the response string.

As for `HSLErrLib::ErrGetDataAt(3)`, it just happens that error data that we use to set o_stepReturn is set at index 3 in the error value for a function. It seems to be called somewhat redundantly in some PyHamilton functions, such as where we assign o_stepReturn to it and then overwrite o_stepReturn with a different value.

For simple equipment, you generally don't have to worry about `HSLErrLib::ErrGetDataAt(3)`. Just set a 1 if the function passes and a 0 if not. `HSLErrLib::ErrGetDataAt(3)` provides more details if that is necessary.

**Comment by melkonyan** [comment]
Hi Stefan. Thanks for the explanations, I got the gist. If it's not urgent, I'm happy to submit a fix in the next couple of days.

**Comment by stefangolas** [comment]
Thank you! We really appreciate the contributions.

**Comment by stefangolas** [comment]
@melkonyan Hi,

I'm reopening this because I think we are both confused about something with the HHS response codes.

In the version of PyHamilton that you said was returning faulty error codes from HHS, we had already implemented inverters on every function that I've seen
![invert](https://user-images.githubusercontent.com/32437678/236096618-2210cee8-8c0e-47b2-acc0-b8fb4097d167.png)

Here we see the code manually overrides a successful HHS command to return a 1, and an error will return a 0. Now it's possible that your change might be preferable to the previous implementation, but "pyhamilton interprets all successful HHS operations as failures." could not have been attributable to the change you implemented.
