### ISSUE TITLE
Feature of error handling

### ISSUE THREAD

**Issue by weihuajiang** [dgretton/pyhamilton#31]
feature of error handling in venus software is very important, it can be used in many situation. We can set default error handling for every action, then these errors like no tip error can be handled automatically, and we can achieve longer walk-away time.

**Comment by stefangolas** [comment]
Errors are already handled in Venus and passed up to Python for most cases. You can catch a no tip error and use try except in Python.

**Comment by weihuajiang** [comment]
this is only exception handling, but not setting default error handling.  For every step in venus, error handling can be set for each error,  during run when the error happens, the recovery will be performed,  e.g. you can set Next for no tip error, then STAR will pickup the next tip when no tip error. But if you do not set the error handling, a dialog will be shown and application will wait for your selection..
![errorHandling](https://github.com/dgretton/pyhamilton/assets/12489873/0a4fac46-f6b3-4f88-a6bb-218e3346cf8e)

**Comment by weihuajiang** [comment]
Error handling is a very useful feature in venus, it can permit long run of walk away. This is very important feature to control STAR/STARlet in venus programming, I think it will be the same for python. I checked your code, the python code control STAR by communicating with venus which running the STAR_OEM.hsl, but in STAR_OEM.hsl, there is no code for setting the default error handling.

```
        if (commandFromServer == "initialize")
        {
            HSLJsonLib::GetIntegerProperty(objJSONFromServer, Translate("initializeAlways"), initializeAlways);
            STAR_OEM_TOOLKIT::Initialize(ML_STAR, initializeAlways, o_stepReturn);
            TrcTrace(Translate("Init step return:"), o_stepReturn);
            SendStepReturnToServer(commandFromServer, o_stepReturn, Translate(""), Translate(""), Translate(""), id);
        }
```

**Comment by stefangolas** [comment]
![errorhandling](https://github.com/dgretton/pyhamilton/assets/32437678/237daa2e-7995-4c5a-9f11-ba893bd990f1)

Here is the corresponding window for the PyHamilton tip pickup command in STAR_OEM_toolkit. As you can see the Cancel box is selected, which results in user defined error handling. I encourage you to run the command yourself and verify the behavior. If anything is confusing or seems incorrect, please let me know. But my inspection of the code indicates that there is error handling for no tips.

Furthermore in oemerr.py there is this entry in HAMILTON_ERROR_MAP  = {.., 8: NoTipError, ..}.

And this corresponding class.
class NoTipError(HamiltonStepError):
    """
    Tip is missing or not picked up.
    """
    pass

**Comment by weihuajiang** [comment]
yes, cancel means that all errors will be throwed as exception, then we have to handled the error in the code. But actually Next and Bottom is really helpful for no tip error, wrong tip error and insufficient liquid error. If we forget to handle with these error, the script will stop with exception due to these simple problems. The default error handling is really useful, otherwise we have to handle all the errors and it will be a complex work. Venus actual can help us to do a lot,  it can handle with all these errors properly. why do not keep it work in python? I think it will bring many benefits if we can set the default error handling. So I suggest this feature. 

We are developing STAR toolkit with c#, and we are working on the default error handling. Following code is what we do with default error handling.

```csharp
ErrorRecoveryOptions options = new ErrorRecoveryOptions();
options.Add(MainErrorEnum.NoTipError, new ErrorRecoveryOption() { Recovery = RecoveryAction.Next});
options.Add(MainErrorEnum.NotExecutedError, new ErrorRecoveryOption() { Recovery = RecoveryAction.Cancel });
try
{
  ML_STAR.Channel.PickupTip(cnts, options);
}
catch (STARException e)
{
  foreach (ModuleError err in e.ModuleErrors)
  {
    Console.WriteLine(err.Module + " " + err.MainError + ":" + err.SlaveError + " " + err.LabwareId + ", " + err.PositionId);
  }
}
```

**Comment by stefangolas** [comment]
The point of PyHamilton is to give Python as much control as possible, so it would not be in line with the design principles to do this in Venus. Furthermore, the way tip indexes are applied means there is not always a default "next tip" in the sequence.

If you want to apply universal error handling on tip_pick_up and aspirate commands, I recommend applying a try-except decorator to these functions and then using the decorated functions. For example:

```
def except_no_tip(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except NoTipError as e:
            print("Excepting no tip")
    
    return wrapper

tip_pick_up = except_no_tip(tip_pick_up)
```

**Comment by weihuajiang** [comment]
OK, I know how to use try catch to handle these errors. Default error handling is a good feature for venus, without it we have to handle many errors for every step, like step loss, no barcode, barcode mask, no tip, wrong tip, clot, improper aspiration, not executed and so on. Any error which is forgot to handle, may lead script crash.

Thanks for your information.
