### ISSUE TITLE
Syntax Error When Testing PyHamilton install

### ISSUE THREAD

**Issue by bking-encodia** [dgretton/pyhamilton#33]
Hello going through installation steps, started with clean environment, installed Venus 4.5 and all prereqs. Got to the point when you test your PyHamilton installation. When running 
`py robot_method.py`
The simulator does start up but then get error below:

![image](https://github.com/user-attachments/assets/cdd7ffa5-4c3b-40cb-ae67-9d5f404d18dc)

Is something missing from Venus install? I selected defaults for Support Software.
I tried to look this up in the forum but it appears labautomaton.io is down. Thanks

**Comment by bking-encodia** [comment]
Was missing some dependencies from support software. Got the test working. thanks

**Comment by stefangolas** [comment]
You must be missing some libraries in Venus. Can you paste a screenshot of the trace file so I can see which ones?

**Comment by zleszczynska** [comment]
<img width="2175" height="300" alt="Image" src="https://github.com/user-attachments/assets/8a2262b7-35bf-4958-b320-5f0efdfc9c36" />
