### ISSUE TITLE
Support for CO-RE gripper?

### ISSUE THREAD

**Issue by jendas1** [dgretton/pyhamilton#6]
I saw there is a function for moving places using ISWAP, is there a way how to move plates using CO-RE grippers? 

([this video](https://www.youtube.com/watch?v=xm-knlv-3N0) shows how CO-RE gripper works)

**Comment by Golaszewski** [comment]
There isn't right now but we are going to add that soon.

**Comment by stefangolas** [comment]
@jendas1 It's added now. Check out gripGet in defaultcmds.py
